# WASI/WASIX local connection plugin - executes modules in-process
#
# This plugin replaces subprocess.Popen with exec() to run ansible modules
# in the same Python interpreter. Required because WASI/WASIX cannot spawn
# new processes.
#
# Copyright: (c) 2025
# License: MIT

from __future__ import annotations

DOCUMENTATION = """
    name: wasi_local
    short_description: execute on controller without subprocess
    description:
        - This connection plugin executes tasks in-process without subprocess.
        - Designed for WASI/WASIX environments where process spawning is unavailable.
        - Only supports localhost execution.
    author: rust-ansible
    version_added: "0.1"
    notes:
        - This plugin is for WASI/WASIX environments only.
        - Does not support become/privilege escalation.
        - Only localhost execution is supported.
"""

import io
import os
import re
import shutil
import sys
import traceback
import typing as t

from ansible.errors import AnsibleError, AnsibleFileNotFound
from ansible.module_utils.common.text.converters import to_bytes, to_text, to_native
from ansible.plugins.connection import ConnectionBase
from ansible.utils.display import Display
from ansible.utils.path import unfrackpath

display = Display()

# Compiled patterns for ansible command recognition.
# These match the command formats generated by ansible's action plugins.
_RE_PYTHON_DISCOVERY = re.compile(r'command -v.*python')
_RE_PYTHON_AVAILABILITY = re.compile(r"python\d*['\"]?\s+&&\s+sleep\s+0")
_RE_ECHO = re.compile(r"echo\s+([^\s;]+)")
_RE_MKDIR = re.compile(r'mkdir\s+-p\s+([^\s;]+)')
_RE_SCRIPT_PATH = re.compile(r'(/[^\s\'"]+\.py)')


class Connection(ConnectionBase):
    """WASI/WASIX local connection - executes modules in-process"""

    transport = 'wasi_local'
    has_pipelining = True

    def __init__(self, *args: t.Any, **kwargs: t.Any) -> None:
        super(Connection, self).__init__(*args, **kwargs)
        self.cwd = None
        self.default_user = os.environ.get('USER', 'wasi')

    def _connect(self) -> 'Connection':
        """Connect to local host - nothing to do"""
        self._play_context.remote_user = self.default_user
        if not self._connected:
            display.vvv(
                f"ESTABLISH WASI LOCAL CONNECTION FOR USER: {self._play_context.remote_user}",
                host=self._play_context.remote_addr
            )
            self._connected = True
        return self

    def _exec_in_namespace(
        self,
        script_content: bytes,
        script_name: str,
        in_data: bytes | None = None,
    ) -> tuple[int, bytes, bytes]:
        """
        Execute script content in an isolated namespace, capturing output.

        This is the core execution method shared by file-based and pipelined
        module execution. Ansible modules are trusted code — they run with
        full access to builtins inside the WASI sandbox.

        Args:
            script_content: Raw bytes of the Python script to execute.
            script_name: Filename for tracebacks (real path or '<pipelined>').
            in_data: Optional stdin data for pipelined execution.

        Returns:
            Tuple of (exit_code, stdout_bytes, stderr_bytes).
        """
        original_stdin = sys.stdin
        if in_data:
            sys.stdin = io.TextIOWrapper(io.BytesIO(in_data), encoding='utf-8')

        original_stdout = sys.stdout
        original_stderr = sys.stderr
        captured_stdout = io.StringIO()
        captured_stderr = io.StringIO()
        sys.stdout = captured_stdout
        sys.stderr = captured_stderr

        exit_code = 0

        try:
            exec_globals = {
                '__name__': '__main__',
                '__file__': script_name,
                '__builtins__': __builtins__,
            }
            exec(compile(script_content, script_name, 'exec'), exec_globals)

        except SystemExit as e:
            exit_code = e.code if isinstance(e.code, int) else (1 if e.code else 0)
            display.debug(f"WASI: Module exited with code {exit_code}")

        except Exception as e:
            exit_code = 1
            traceback.print_exc(file=captured_stderr)
            display.debug(f"WASI: Module execution failed: {e}")

        finally:
            sys.stdout = original_stdout
            sys.stderr = original_stderr
            sys.stdin = original_stdin

        stdout_bytes = captured_stdout.getvalue().encode('utf-8')
        stderr_bytes = captured_stderr.getvalue().encode('utf-8')

        display.debug(f"WASI: Command completed with rc={exit_code}")
        if stderr_bytes:
            display.debug(f"WASI: stderr={stderr_bytes[:500]}")

        return (exit_code, stdout_bytes, stderr_bytes)

    def _save_debug_script(self, filename: str, content: bytes) -> None:
        """Save script to disk for debugging (only at -vvvv or higher)."""
        if display.verbosity < 4:
            return
        debug_path = f'/workspace/.ansible/{filename}'
        try:
            os.makedirs(os.path.dirname(debug_path), exist_ok=True)
            with open(debug_path, 'wb') as df:
                df.write(content)
            display.vvvv(f"WASI: Saved script to {debug_path}",
                         host=self._play_context.remote_addr)
        except Exception:
            pass

    def exec_command(
        self,
        cmd: str,
        in_data: bytes | None = None,
        sudoable: bool = True
    ) -> tuple[int, bytes, bytes]:
        """
        Execute command in-process instead of via subprocess.

        For WASI/WASIX, we intercept the Python command and exec() it directly,
        capturing stdout/stderr and the exit code.
        """
        super(Connection, self).exec_command(cmd, in_data=in_data, sudoable=sudoable)

        display.debug("in wasi_local.exec_command()")

        cmd_str = to_text(cmd) if isinstance(cmd, bytes) else cmd
        display.vvv(f"EXEC (in-process) {cmd_str}", host=self._play_context.remote_addr)

        if in_data:
            display.vvv(f"WASI: in_data length: {len(in_data)}",
                        host=self._play_context.remote_addr)

        return self._dispatch_command(cmd_str, in_data)

    def _dispatch_command(
        self,
        cmd: str,
        in_data: bytes | None,
    ) -> tuple[int, bytes, bytes]:
        """
        Route a command to the appropriate handler.

        Ansible generates several shell command patterns during task execution.
        We match each pattern and handle it without a real shell.
        """
        # Python discovery: "echo FOUND; command -v 'python3.13'; ..."
        if _RE_PYTHON_DISCOVERY.search(cmd):
            display.debug("WASI: Python discovery command")
            return (0, b'FOUND\n/usr/bin/python3\n', b'')

        # Pipelining: module script arrives via in_data, cmd is just "python3"
        if in_data and 'python' in cmd and '.py' not in cmd:
            display.debug(f"WASI: Pipelining mode, {len(in_data)} bytes from in_data")
            self._save_debug_script('last_pipelined_script.py', in_data)
            return self._exec_in_namespace(in_data, '<pipelined>')

        # Python availability check: "/bin/sh -c '/usr/bin/python3 && sleep 0'"
        if _RE_PYTHON_AVAILABILITY.search(cmd) and not in_data:
            display.debug("WASI: Python availability check")
            return (0, b'', b'')

        # echo commands used for temp directory setup
        if cmd.startswith('echo ') or "'echo " in cmd or '"echo ' in cmd:
            match = _RE_ECHO.search(cmd)
            if match:
                output = match.group(1).strip("'\"")
                return (0, output.encode() + b'\n', b'')
            return (0, b'\n', b'')

        # mkdir -p for temp directories
        if 'mkdir' in cmd:
            match = _RE_MKDIR.search(cmd)
            if match:
                path = match.group(1).strip("'\"")
                try:
                    os.makedirs(path, exist_ok=True)
                    return (0, b'', b'')
                except Exception as e:
                    return (1, b'', f'mkdir failed: {e}'.encode())

        # chmod is a no-op in WASI
        if 'chmod' in cmd:
            return (0, b'', b'')

        # rm for cleanup is a no-op
        if cmd.startswith('rm ') or '/rm ' in cmd:
            return (0, b'', b'')

        # File-based module execution: extract .py path from the command
        py_match = _RE_SCRIPT_PATH.search(cmd)
        if py_match:
            return self._exec_script_file(py_match.group(1), in_data)

        display.warning(f"WASI: Cannot parse command as Python script: {cmd}")
        return (1, b'', f'WASI connection cannot execute non-Python commands: {cmd}'.encode())

    def _exec_script_file(
        self,
        script_path: str,
        in_data: bytes | None,
    ) -> tuple[int, bytes, bytes]:
        """Load a Python script from disk and execute it in-process."""
        display.debug(f"WASI: Executing Python script: {script_path}")

        try:
            script_path_bytes = to_bytes(script_path, errors='surrogate_or_strict')
            with open(script_path_bytes, 'rb') as f:
                script_content = f.read()
        except FileNotFoundError:
            return (1, b'', f'Script not found: {script_path}'.encode())
        except Exception as e:
            return (1, b'', f'Failed to read script {script_path}: {e}'.encode())

        display.vvv(f"WASI: Script preview: {script_content[:500]}",
                     host=self._play_context.remote_addr)
        self._save_debug_script('last_module_script.py', script_content)

        return self._exec_in_namespace(script_content, script_path, in_data)

    def put_file(self, in_path: str, out_path: str) -> None:
        """Transfer a file from local to local"""
        super(Connection, self).put_file(in_path, out_path)

        in_path = unfrackpath(in_path, basedir=self.cwd)
        out_path = unfrackpath(out_path, basedir=self.cwd)

        display.vvv(f"PUT {in_path} TO {out_path}", host=self._play_context.remote_addr)

        if not os.path.exists(to_bytes(in_path, errors='surrogate_or_strict')):
            raise AnsibleFileNotFound(f"file or module does not exist: {to_native(in_path)}")

        try:
            shutil.copyfile(
                to_bytes(in_path, errors='surrogate_or_strict'),
                to_bytes(out_path, errors='surrogate_or_strict')
            )
        except shutil.Error:
            raise AnsibleError(f"failed to copy: {to_native(in_path)} and {to_native(out_path)} are the same")
        except OSError as ex:
            raise AnsibleError(f"Failed to transfer file to {out_path!r}.") from ex

    def fetch_file(self, in_path: str, out_path: str) -> None:
        """Fetch a file from local to local"""
        super(Connection, self).fetch_file(in_path, out_path)
        display.vvv(f"FETCH {in_path} TO {out_path}", host=self._play_context.remote_addr)
        self.put_file(in_path, out_path)

    def connection_lock(self) -> None:
        """No-op for WASI - no file locking needed for in-process execution"""
        pass

    def connection_unlock(self) -> None:
        """No-op for WASI - no file locking needed for in-process execution"""
        pass

    def reset(self) -> None:
        pass

    def close(self) -> None:
        """Terminate the connection"""
        self._connected = False
